apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-xjju
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-xjju
    app.kubernetes.io/part-of: test-devfile-sample-go-basic-1
  name: devfile-sample-xjju
spec:
  ports:
  - name: "3001"
    port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: devfile-sample-xjju
status:
  loadBalancer: {}
